apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    tier: frontend
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: react_app_v2
        image: react_app_v2
        ports:
        - containerPort: 80
        