apiVersion: v1
kind: Secret
metadata:
    name: mongo-secret
    namespace: quiz
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly90YWhzZWVuaXNsYW1pYW45MDA6dGFoc2VlbjE3NkBjbHVzdGVyMC51YXh6dy5tb25nb2RiLm5ldC9xdWl6ekFwcAo=
              ## base 64 encoded string, see docs
